# -*- coding: utf-8 -*-
"""test_stuff.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RaaTIUo4u4U32aHvFnxQSI36ag6l24NJ
"""

from stuff import run_stuff

def test_run_stuff():
    result = run_stuff()
    assert result == 1